databases:
  - name: airvault-postgres
    databaseName: airvault
    user: airvault
    plan: free

services:
  - type: web
    name: airvault-app
    env: docker
    region: oregon
    dockerfilePath: ./payload-app/Dockerfile
    dockerContext: ./payload-app
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URI
        fromDatabase:
          name: airvault-postgres
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: airvault-postgres
          property: connectionString
      - key: REDIS_URL
        value: redis://default:gQAAAAAAAWi-AAIgcDI4MDc0OWNhOGNjM2E0ZDUwYTA0YzY2ZWI3YWVlYzQ2Zg@skilled-anchovy-92350.upstash.io:6379
      - key: PAYLOAD_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: pkc-12576z.us-west2.gcp.confluent.cloud:9092
      - key: KAFKA_SASL_USERNAME
        value: 2JMLZXEW7LZFDXTD
      - key: KAFKA_SASL_PASSWORD
        value: cfltriDBpmf7Qm02ByjrJel6YOeO8zTAqFn3ghYK3DiQ8GqroIPQTSNHBS840YpQ
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN
      - key: KAFKA_DELAY_TOPIC
        value: flight-delays
      - key: KAFKA_CLAIM_TOPIC
        value: claim-processed
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: noreply@sheetinvoicer.com
      - key: NEXT_PUBLIC_SERVER_URL
        value: https://airvault-app.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://airvault-app.onrender.com

